# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
  - cron: "0 2,14 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Clear files...
        run: | 
          rm -f unified.txt

      # Runs a set of commands using the runners shell
      - name: Download files...
        run: |
          wget https://block.energized.pro/unified/formats/filter -o unified.txt
          
      - name: Upload changes...
        uses: EndBug/add-and-commit@v7
        with:
          author_email: dothq-robot@users.noreply.github.com
          message: '🍱 Upload mirrored files'
